name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: "1"

jobs:
  tests:
    name: "CI"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install latest dependencies"
        run: |
          composer update ${{ env.COMPOSER_FLAGS }}

      - name: "Run tests"
        run: "vendor/bin/simple-phpunit --verbose"

  phpstan_tests:
    name: "CI PHPStan Ext"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "8.3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install latest dependencies"
        run: |
          # Require PHPUnit directly bypassing the symfony bridge
          composer remove symfony/phpunit-bridge --dev --no-update
          composer require phpunit/phpunit:^9 --dev --no-update
          composer update ${{ env.COMPOSER_FLAGS }}

      - name: "Run tests"
        run: vendor/bin/phpunit -c phpunit-phpstan.xml.dist
